AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cwl-metrics-origin

  Sample SAM Template for cwl-metrics-origin

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Parameters:
  FunctionRoleArn:
    Type: String
    Default: ''
  SlackChannel:
    Type: String
    Description: |-
      Channel, private group, or IM channel to send message to.
      See: https://api.slack.com/methods/chat.postMessage#channels
  SlackTokenParameterNameWithoutLeadingSlash:
    Type: String
    Default: cwl_metrics_origin/slack_token
    AllowedPattern: ^[^/].*$
    Description: |-
      Parameter name (without leading slash) of Systems Manager
      Parameter Store storing Slack token.
      See: https://api.slack.com/tutorials/tracks/getting-a-token

Conditions:
  FunctionRoleArnNotSpecified:
    !Equals [!Ref FunctionRoleArn, '']

Resources:
  CwlMetricsOriginFunctionRole: 
    Type: 'AWS::IAM::Role' 
    Condition: FunctionRoleArnNotSpecified
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17 
        Statement: 
          - Effect: 'Allow' 
            Principal: 
              Service: 
                - 'lambda.amazonaws.com' 
            Action: 
              - 'sts:AssumeRole' 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLogsReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      Policies:
        - PolicyName: allow-ssm-get-parameter
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: !Join
                  - ''
                  - - 'arn:'
                    - !Ref AWS::Partition
                    - ':ssm:'
                    - !Ref AWS::Region
                    - ':'
                    - !Ref AWS::AccountId
                    - ':parameter/'
                    - !Ref SlackTokenParameterNameWithoutLeadingSlash

  CwlMetricsOriginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions
      Handler: cwl_metric_origin/app.lambda_handler
      Runtime: python3.9
      Role: !If [FunctionRoleArnNotSpecified, !GetAtt CwlMetricsOriginFunctionRole.Arn, !Ref FunctionRoleArn]
      Environment: 
        Variables:
          SLACK_CHANNEL: !Ref SlackChannel
          SLACK_TOKEN_PARAM: !Ref SlackTokenParameterNameWithoutLeadingSlash

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CwlMetricsOriginFunction:
    Description: CloudWatch Logs Metrics Origin Lambda Function ARN
    Value: !GetAtt CwlMetricsOriginFunction.Arn
  CwlMetricsOriginFunctionRole:
    Description: IAM Role created for CloudWatch Logs Metrics Origin function
    Value: !GetAtt CwlMetricsOriginFunctionRole.Arn
